name: Build Kivy App to APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk python3-pip libffi-dev python3-venv libssl-dev \
            libjpeg-dev libfreetype6-dev zlib1g-dev autoconf automake libtool build-essential \
            libgl1-mesa-dev libgles2-mesa-dev xvfb libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
            libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libtiff5-dev libx11-dev
        pip3 install --upgrade pip
        pip3 install Cython==0.29.21
        pip3 install kivy[base] kivy[full] easyocr

    - name: Install Buildozer
      run: |
        pip3 install buildozer

    # تحديث buildozer.spec مباشرة بدلاً من إعادة تشغيل init
    - name: Update buildozer.spec for APK
      run: |
        sed -i 's/^# \(android\.api =\)/\1 31/' buildozer.spec
        sed -i 's/^# \(android\.ndk =\)/\1 21b/' buildozer.spec
        sed -i 's/^# \(android\.minsdk =\)/\1 21/' buildozer.spec
        sed -i 's/^# \(android\.sdk =\)/\1 21/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: ./bin/*.apk
